### ISSUE TITLE
Build error [1.16.2]

### ISSUE THREAD

**Issue by MrSlimeDiamond** [LoomDev/Loom#27]
When I run `mvn package` I get the following error:
```
[ERROR] Failed to execute goal on project loom: Could not resolve dependencies for project org.loomdev:loom:jar:1.16.2-SNAPSHOT: The following artifacts could not be resolved: org.loomdev:minecraft-server:jar:1.16.2-SNAPSHOT, org.loomdev:loom-api:jar:1.16.2-SNAPSHOT: Could not find artifact org.loomdev:minecraft-server:jar:1.16.2-SNAPSHOT ->
```

Full log: https://pastebin.com/gp3KywaS

**Comment by thatgoofydev** [comment]
Did you run `./loom s` in the Loom root as it says in the README? That is supposed to install that dependency in your local maven repository.

On windows there is a problem with the script where it does not know the wget command. If that is the case you can download [fernflower.jar](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/raw/bin/fernflower.jar) manually and place it in the ./tools directory.

Keep in mind 1.16.2 is a very early version of loom where we did not have good tooling setup. I also DO NOT recommend using this version for several reasons. (Very old api design, error prone, ...) Loom is still in development and does not yet have a what I consider stable version.

**Comment by MrSlimeDiamond** [comment]
I do remember running ./loom s but I might have not done it correctly. I'll retry it, and I'm using 1.16.2 because the latest is a snapshot :P

**Comment by MrSlimeDiamond** [comment]
I did `./loom s` and got this:
Full log: https://pastebin.com/YYaNQ7Mp
Looks like an out of memory error

**Comment by TheKodeToad** [comment]
You're probably just going to have to wait until the full 1.17 release if you don't want to use snapshots. 1.16.5 is available, but it does not include many of the newer changes (unless changes are backported). The 21w11a branch (which should be the default) is 133 commits ahead.

**Comment by thatgoofydev** [comment]
> Looks like an out of memory error

It is, it means that you have to assign more memory to your maven. (One way of doing this is https://stackoverflow.com/a/30441186)

However, I do agree with the points made by @TheKodeToad. (ps: atm we do not backport any changes)

**Comment by MrSlimeDiamond** [comment]
okay, I ran on 21w11a, and:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project loom-api: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```
(also, sorry for being late)

**Comment by thatgoofydev** [comment]
> ```
> The environment variable JAVA_HOME is not correctly set.
> ```

The error already states what the problem is. You can look up how to correctly setup the JAVA_HOME variable for you operation system on google.
